### ISSUE TITLE
Uncatched exception if connection restored

### ISSUE THREAD

**Issue by NektoDron** [JKorf/CryptoExchange.Net#115]
**Describe the bug**
Uncatched exception is throw if connection restored

**To Reproduce**
I think it on binance sockets

**Expected behavior**
Exception should be handled

**Debug logging**
15:40:40.42[2]FATAL:UnobservedTaskException: AggregateException:
AggregateException:
InvalidOperationException:Socket 40 Can't send data when socket is not connected:   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.Send(String data)
   at CryptoExchange.Net.Sockets.SocketConnection.Send(String data)
   at CryptoExchange.Net.Sockets.SocketConnection.SendAndWaitAsync[T](T obj, TimeSpan timeout, Func`2 handler)
   at CryptoExchange.Net.SocketClient.SubscribeAndWaitAsync(SocketConnection socketConnection, Object request, SocketSubscription subscription)

https://www.screencast.com/t/T4ZeMCTbVfJP

**Comment by JKorf** [comment]
This should've been resolved, let me know if you're stilling getting this
