### ISSUE TITLE
CryptoExchangeWebSocketClient stuck in invalid state when receive loop finishes

### ISSUE THREAD

**Issue by vgpro54321** [JKorf/CryptoExchange.Net#159]
I am using Kucoin.net package to receive market data. Sometimes sockets seems to be disconnected by remote host and there are no reconnect attempts following this situation, so market data simply stops coming.

The logs (at the end) indicate that Receive loop terminates. 

I tried to troubleshoot what is going on.

There is a receive loop in CryptoExchangeWebSocketClient. I am not sure I fully understand the whole flow but here goes my troubleshooting thoughts.

ProcessAsync is waiting for Send and Receive loops to terminate. 

```
private async Task ProcessAsync()

  var sendTask = SendLoopAsync();
                var receiveTask = ReceiveLoopAsync();
                var timeoutTask = Parameters.Timeout != null && Parameters.Timeout > TimeSpan.FromSeconds(0) ? CheckTimeoutAsync() : Task.CompletedTask;
                await Task.WhenAll(sendTask, receiveTask, timeoutTask).ConfigureAwait(false);
                _log.Write(LogLevel.Debug, $"Socket {Id} processing tasks finished");
```

Receive loop catches exception (unexpected disconnect) and terminates without re-throw.

```
private async Task ReceiveLoopAsync()

   try
                        {
                            receiveResult = await _socket.ReceiveAsync(buffer, _ctsSource.Token).ConfigureAwait(false);
                            received += receiveResult.Count;
                            lock (_receivedMessagesLock)
                                _receivedMessages.Add(new ReceiveItem(DateTime.UtcNow, receiveResult.Count));
                        }
                        catch (OperationCanceledException)
                        {
                            // canceled
                            break;
                        }
                        catch (Exception wse)
                        {
                            // Connection closed unexpectedly
                            OnError?.Invoke(wse);
                            _closeTask = CloseInternalAsync();
                            break;
                        }
```

Send loop (market data subscription) does not receive events to send, it simply waits for sendEvent and never finds out socket disconnected. As a result, Send loop never finishes when socket is disconnected and socket is stuck not receiving data and not reconnecting. Perhaps it should wait with timeouts and check socket state?
```
private async Task SendLoopAsync()

 while (true)
                {
                    if (_ctsSource.IsCancellationRequested)
                        break;

                    await _sendEvent.WaitAsync().ConfigureAwait(false);
```

Log file quote
```
2022-10-13T10:24:16.2531339-04:00  [WRN] Kucoin     | Socket 3 error: Websocket error code ConnectionClosedPrematurely, details: WebSocketException - The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.<ReceiveLoopAsync>d__69.MoveNext()
 (bbc45183)
2022-10-13T10:24:16.2531339-04:00  [DBG] Kucoin     | Socket 3 Receive loop finished (029390f5)

```

**Comment by JKorf** [comment]
Hi, sorry for the delay. When the exception occures in the receive loop it calls CloseInternal(). That will call both _ctsSource.Cancel() and _sendEvent.Set(). The _sendEvent.Set() will make the send loop continue past the WaitAsync in the same way it would normally when a message is queued. 
So I don't think this is the  issue. I appreciate any insights though. I haven't found a way an exception in the receive loop would cause the send loop to not finish, but based on your logging there is something going on..
